---
language: python
python:
- 2.7
env:
  - DJANGO=1.9
  - DJANGO=1.10

install:
  - pip install Django==$DJANGO
  - pip install oncondition

script:
  - python setup.py test

branches:
  only:
    - master
